### ISSUE TITLE
I cannot able to generate the report . Please help me 

### ISSUE THREAD

**Issue by vishalsvayam** [lequal/sonar-cnes-export-plugin#3]
I have installed the sonar-cnes-export-plugin in the soanrqube plugin directory . 

What I did is 
1) downloaded the zip from github
2) unzipped the zip file 
3) I have copied it into the sonarqube plugin directory but still I can't find way to export report from sonarqube . Please help me .

**Comment by vishalsvayam** [comment]
The instruction says 

Setup a SonarQube instance
Install the plugin
Go to More > CNES Export
Export a profile


But I cannot find the plugin should I run a comman d to generate the plugin or should I copy the directory as a whole into sonarqube plugin directory

**Comment by begarco** [comment]
Zip file do not contain any jar but only source code.

You can find the jar file here: https://github.com/lequal/sonar-cnes-export-plugin/releases.
