### ISSUE TITLE
How to export a profile in Sonar cnes 

### ISSUE THREAD

**Issue by vishalsvayam** [lequal/sonar-cnes-export-plugin#4]
I can able to install Sonar cnes plugin . When I click on More> CNES EXPORT . It shows empty page . Can you please guide me on to Export a profile. I ran the scan and I can see that in scan overview page. Please help me on this.

**Comment by begarco** [comment]
Which version of SonarQube do you use?

**Comment by Sancretor** [comment]
No answer for nearly a year, we consider this issue as outdated.
